### ISSUE TITLE
API to retrieve list of tokens that fees can be accepted in and the amount to be paid in that token

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#1114]
As a wallet application provider,
I want to have an API endpoint that accepts token addresses and returns a list of tokens that are accepted as fees and how much I have to pay in each of those tokens,
So that I can make a transaction with fee tokens that are accepted by the OmiseGO Network.

**Comment by unnawut** [comment]
/fees.all is now available
