### ISSUE TITLE
User can send fee as an input to the payment transaction

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#1117]
As an end-user wallet,
I want to be able to make an end-to-end transaction with a particular fee token and amount,
So that my transaction will get accepted by the operator.

This story includes a user making transaction from `/transaction.create` endpoint to a successful `/transaction.submit_typed` end to end.

**Comment by jrhite** [comment]
Still learning walllet, are these requests made via `omg-js` or direct to `watcher`.

**Comment by pnowosie** [comment]
> This story includes a user making transaction from /transaction.create endpoint to a successful /transaction.submit end to end.

@Pongch Did you mean: `/transaction.submit_typed` :question:

**Comment by unnawut** [comment]
no fee, no transfer now yo
