### ISSUE TITLE
exit game contract should be retrieved from contracts

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/elixir-omg#1206]
Plasma contracts allow us to dynamically retrieve `exitGames(uint256)` for specific payment type. We should do that so that we don't have to specify exit game contract address. For reference check `Itest.StandardExitClient.get_exit_game_contract_address/1`

**Comment by unnawut** [comment]
Already implemented in https://github.com/omgnetwork/elixir-omg/blob/master/apps/omg_eth/lib/omg_eth/release_tasks/set_contract.ex#L97-L108
