### ISSUE TITLE
Revisit the gas price selection mechanism and unit tests

### ISSUE THREAD

**Issue by pdobacz** [omgnetwork/elixir-omg#1268]
https://github.com/omisego/elixir-omg/pull/1258 brought in a refactor of `BlockQueue.CoreTest` where a more behavior-driven approach was taken.

This brought to light several surprising edge-cases in how `BlockQueue.Core` operates the gas prices. (see `NOTE`s left in the test file, for example here: https://github.com/omisego/elixir-omg/blob/master/apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs#L275, here: https://github.com/omisego/elixir-omg/blob/master/apps/omg_child_chain/test/omg_child_chain/block_queue/core_test.exs#L442 and in following lines ).

Despite this being the case, the gas price selection mechanism seemed to have behaved fine in the testnet deployments we ran, so I'm reluctant to file this as a bug without digging deeper in.

What needs to be done in this issue is:
  - analyze the flows that `BlockQueue.Server` has and how it calls into it's logic module `BlockQueue.Core` with respect to the gas price selection mechanism
  - in this context, rethink the annotated test cases and decide if the test is off or there in fact are edge cases where the gas price selection won't work as intended
  - fix (possibly both impl and tests if the test just verify an incorrect behavior)

**Comment by boolafish** [comment]
From logs recently, I have observed that it would try to re-submit same block with lower gas.
I am not 100% following what should be the "right logic" to submit now, but retrying with lower gas seems not making much sense to me. Lower gas should be applied to next submission instead, right? No miner is going to accept the lower gas price tx anyway if seeing the previous tx already.

**Comment by unnawut** [comment]
> From logs recently, I have observed that it would try to re-submit same block with lower gas.
> I am not 100% following what should be the "right logic" to submit now, but retrying with lower gas seems not making much sense to me. Lower gas should be applied to next submission instead, right? No miner is going to accept the lower gas price tx anyway if seeing the previous tx already.
> 
> ref this to #1527

I think there's a potential bug here where if eth block time is longer than usual it will go into `gas_price_lowering_factor`: https://github.com/omgnetwork/elixir-omg/blob/master/apps/omg_child_chain/lib/omg_child_chain/block_queue/core.ex#L433

```
      with ..,
           true <- eth_blocks_gap_filled?(parent_height, lastchecked_parent_height, eth_gap_without_child_blocks),
           .. do
        gas_price_raising_factor
      else
        _ -> gas_price_lowering_factor
      end
```

This is addressed in the new PR where it will not lower the price: https://github.com/omgnetwork/elixir-omg/pull/1575/files#diff-170e6f539bb8104a78455877a4ff7e85R148

```elixir
    cond do
       latest.parent_height - state.last_parent_height < state.eth_gap_without_child_blocks ->
         state
    ..
```

**Comment by unnawut** [comment]
Closing as it's being tracked in another issue
