### ISSUE TITLE
performance of FreshBlocks

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/elixir-omg#1290]
I anticipate that FreshBlocks will become a performance bottleneck for ChildChains `block.get`.
I don't have data to backup my claim (Datadog is ded). But from the code, the problem is the following:
- the code is funneled twice. First at `FreshBlocks` being a single GenServer and later down the stack fetching the old blocks (those that are not in process dict) from RocksDB genserver.

I propose the following improvement (I guess *after* we can prove it's not going to scale):
- declare a ETS table with write ownership protection from FreshBlocks
- allow cowboy process to read from ETS with read_concurrency: true

**Comment by InoMurko** [comment]
I see @pdobacz already noticed this https://github.com/omisego/elixir-omg/blob/master/apps/omg_child_chain/lib/omg_child_chain/fresh_blocks/core.ex#L20-L21
👏

**Comment by pdobacz** [comment]
The original idea of `FreshBlocks` was to ease load on the `OMG.DB` when a new block is published. But it was just really a placeholder for something more meaningful. I think with our current state of requirements, knowledge and other scaling endeavors, we might even be better off without it.

Other than that, the suggestion look very good :+1:
