### ISSUE TITLE
Ability to filter transactions by date range in transaction.all

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/elixir-omg#1417]
Gift needs fee amounts on a daily basis for auditing purposes.

My view is that a scalable solution entails calling `/transaction.all` with two filters: address and timestamp range. 

Address functionality already exists, so would like to explore implementing a timestamp range filter. 

Note that UI for auditors to use is a separate question. Could be block explorer or something else.

**Comment by jrhite** [comment]
would recommend taking a look at: https://github.com/swimlane/ngx-datatable/

It's Angular, but it lays out a pretty standard filtering/sorting/paging contract between client/server endpoints. also supports this on either client or server side (server side for this particular issue).

I had a filtering/sorting/paging issue open: https://github.com/omisego/elixir-omg/issues/1215

I closed it for now, but feel free to re-open if it makes sense to.

**Comment by okalouti** [comment]
Closed as `end_datetime` filter has been implemented
