### ISSUE TITLE
CI is failing on master branch

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/elixir-omg#1428]
cc: @unnawut 

https://circleci.com/gh/omisego/elixir-omg/tree/master

**Comment by pgebal** [comment]
I am on that @okalouti.

**Comment by InoMurko** [comment]
@okalouti @pgebal pls elaborate what both of you are looking at/reporting. 
The link is showing failing nightly builds and failing `run_load_test_on_deployed_env`. I think @pgebal is taking `run_load_test_on_deployed_env `. 
@okalouti are you looking at nightly builds failing?

**Comment by pgebal** [comment]
Sorry for not being precise. I am taking `run_load_test_on_deployed_env` @okalouti

**Comment by okalouti** [comment]
Hey @InoMurko. I was pointing to the nightly builds failing, yes.

**Comment by InoMurko** [comment]
cool @okalouti ! there were some attempts already: https://github.com/omisego/elixir-omg/pull/1287

**Comment by pgebal** [comment]
The part with failed load tests is solved. We decided to switch them off until we come up with a good way on how to run them for `build_test_deploy` CI pipeline.

**Comment by InoMurko** [comment]
macos barebuild sometimes fails, I;ll look into that
