### ISSUE TITLE
Fix `Testing & development` section in README.md

### ISSUE THREAD

**Issue by pgebal** [omgnetwork/elixir-omg#1497]
Documentation for https://github.com/omisego/elixir-omg#testing--development is incomplete. I couldn't run tests. There are some issues like wrong paths, permissions.

**Comment by InoMurko** [comment]
It would be really helpful if you explained what the document is missing or is wrong about. Wrong paths/permissions does not describe the problem sufficiently.

**Comment by boolafish** [comment]
I bumped into this when I follow the instruction to run test inside docker

```
bash-5.0$ mix test test/omg_watcher --trace 

SHELL environment variable not set!
** (MatchError) no match of right hand side value: {:error, {:erlexec, {{:shutdown, {:failed_to_start_child, :exec, {:port_existed_with_status, 4}}}, {:exec_app, :start, [:normal, []]}}}}
    test/test_helper.exs:19: (file)
    (elixir 1.10.2) lib/code.ex:917: Code.require_file/2
    (elixir 1.10.2) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir 1.10.2) lib/enum.ex:783: Enum.each/2
```

**Comment by InoMurko** [comment]
this could be because you're running geth already and tests are trying to start another one
