### ISSUE TITLE
Watcher Docker Run fails in logs

### ISSUE THREAD

**Issue by mikedeshazer** [omgnetwork/elixir-omg#1562]
Updated the docket-compose-watcher.yml with my INFURA url and key for mainnet. On mac OS. Ran docker compose: docker-compose -f docker-compose-watcher.yml up -d
Then logged with: docker-compose -f docker-compose-watcher.yml logs -ft
Got this error:
watcher_info_1  | 2020-06-02T09:27:33.667934419Z init terminating in do_boot ({{badmatch,},[{Elixir.ABI.TypeDecoder,decode_uint,2,[{_},{_}]},{Elixir.ABI.TypeDecoder,-decode_type/2-fun-0-,2,[{_},{_}]},{Elixir.Enum,-reduce/3-lists^foldl/2-0-,3,[{_},{_

2020-06-02T09:28:06.415091353Z Crash dump is being written to: erl_crash.dump...done
watcher_info_1  | 2020-06-02T09:28:06.422905068Z [os_mon] cpu supervisor port (cpu_sup): Erlang has closed
watcher_info_1  | 2020-06-02T09:28:06.422980149Z [os_mon] memory supervisor port (memsup): Erlang has closed
watcher_info_1  | 2020-06-02T09:28:06.428735203Z [cmd] /watcher_info_entrypoint exited 1
watcher_info_1  | 2020-06-02T09:28:06.433161777Z [cont-finish.d] executing container finish scripts...
watcher_info_1  | 2020-06-02T09:28:06.434986989Z [cont-finish.d] done.
watcher_info_1  | 2020-06-02T09:28:06.435577370Z [s6-finish] syncing disks.
watcher_info_1  | 2020-06-02T09:28:06.514519808Z [s6-finish] sending all processes the TERM signal.
watcher_info_1  | 2020-06-02T09:28:09.524055403Z [s6-finish] sending all processes the KILL signal and exiting.

Any advise on this?

**Comment by dmitrydao** [comment]
Make sure to double-check the following things:
1.  Environments for `watcher` and `watcher_info` services should correspond with the respective [environments](https://docs.omg.network/environments). These are the values you need to configure:
```
- ETHEREUM_RPC_URL=
- CHILD_CHAIN_URL=
- ETHEREUM_NETWORK=
- AUTHORITY_ADDRESS=
- TXHASH_CONTRACT=
- CONTRACT_ADDRESS_PLASMA_FRAMEWORK=
- CONTRACT_ADDRESS_ETH_VAULT=
- CONTRACT_ADDRESS_ERC20_VAULT=
- CONTRACT_ADDRESS_PAYMENT_EXIT_GAME=
```
2 `ETHEREUM_RPC_URL` should correspond with the full ETH node URL for the specific environment you're using: Ropsten or Mainnet. If you're using Infura or similar providers, they have different tokens for each environment.

**Comment by unnawut** [comment]
Closing as the discussion is stale. Feel free to reopen with more info!
