### ISSUE TITLE
Endpoint: /transaction.merge

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/elixir-omg#1644]
With capability for merge transactions retired from `/transaction.create`, we would like to create a new endpoint (`/transaction.merge`) allowing integrators and users to build logic for merging UTXOs.

**Comment by thec00n** [comment]
I am sure I understand what's proposed here. Let's discuss in the kick off call.

**Comment by pnowosie** [comment]
:+1: for it! 
`/transaction.create` doesn't allow to choose UTXOs and by design contributes to UTXO set crumbling.

```bash
http POST :7434/transaction.merge utxos=[1000000000000, 1000000000001]
http POST :7434/transaction.merge # merges least valuable outputs
```

**Comment by okalouti** [comment]
Expanding on this issue further and recapping a call we had on this yesterday ... cc @nicholasmueller 

Currently, to form a merge transactions, the client fetches UTXOs and forms the transaction body with helpers from `omg-js`.

The idea of a `/transaction.merge` endpoint is to provide more convenience around merge transactions for integrators.

In our current design, the transaction `/transaction.merge` endpoint would take three possible parameters: 

``` json
"address" : hexadecimal string
"inputs": array of utxo positions
"currency": hexadecimal string
```

* if given `inputs`, will fetch the corresponding UTXOs from the database and return a transaction object ready for signing.
* if given `address` and `currency`, fetches the least valuable UTXOs for said currency and returns a transaction object ready for signing. 

Why don't we just use `/transaction.create`? 
- `/transaction.create` selects UTXOs for you. While we are incorporating "stealth merge" logic in the selection logic, this is not the same thing as an intentionally defined merge. 
- `/transaction.create` contains logic for adding fee outputs. We do not want to add logic in there for "no-fee" transactions.

**Comment by unnawut** [comment]
To add on to this part:

> Why don't we just use `/transaction.create`?

There's a bit of past discussion on the same rationales: https://github.com/omgnetwork/elixir-omg/pull/1416#issuecomment-603147771

**Comment by okalouti** [comment]
So that everyone stays up to date, we envision that the first version of the endpoint will accept two sets of parameters: 

You would either pass in: 

1) `utxo_positions` - e.g. `[1000000000000, 1000000000001]`
2) `address` and `currency`

Both will return transaction bodies with typed data. 

In the first case, the endpoint will execute some validation logic.  It will check that all `utxo_positions` correspond to inputs owned by the same address.* Should the `utxo_positions` correspond to inputs of multiple currencies, it will check that each currency includes two inputs or more. 

In the second case, the endpoint will fetch UTXOs for the given address and currency in _ascending_ order of value (i.e. "dust first")

\* _To avoid the introduction of complexity for a use case that is distant, the endpoint will not support two different addresses wanting to merge two inputs each in the same transaction at the moment_

**Comment by okalouti** [comment]
A future feature would be to pass in an `amount` corresponding to the value of a UTXO you want to create from merges, but we are targeting MVP first.

**Comment by okalouti** [comment]
Once again for clarity. The `/transaction.create` endpoint will no longer return a merge transaction (i.e. "intermediate" result) if the users cannot cover a payment transaction in four inputs or less (but has the requisite balances)

Instead. It will return an error message. And the `/transaction.merge` endpoint will be the exclusive avenue for merge transactions. 

cc @Pongch @dmitrydao
