### ISSUE TITLE
Optimise usage of UTXOs in transaction.create

### ISSUE THREAD

**Issue by okalouti** [omgnetwork/elixir-omg#1645]
In line with the objective of reducing the amount of UTXOs on the network, implement logic in  `/transaction.create` to select the maximum number of UTXOs as transaction inputs.

**Comment by okalouti** [comment]
Flow I: 
- Count number of currencies involved in the transaction (incl. fee) 
- Derive the inputs needed for this currency at a minimum. 
- Where there are remaining "spaces", add an input.

**Comment by okalouti** [comment]
_MAX_UTXOS = 4
U: UTXOs needed to cover transfer and fee amount
U = (number of currencies in transaction) x (amount required to cover each currency amount)
U ≤ MAX_UTXOS_ 

| Cases   | Desired Outcome   |  Status | 
|---|---|
|   |   |   |
|   |   |   |   
|   |   |   |

**Comment by okalouti** [comment]
Current UTXO selection flow: 
1. Fetch UTXOs from database and order them by currency and amount. _To do: refactor to use full database query_
2.

**Comment by unnawut** [comment]
☝️  These analyses are pure gold. Thanks!

**Comment by okalouti** [comment]
Pseudo Code

```
stealth_merge(current_utxos, user_utxos_ordered_by_currency_utxos) do
   base_case: = maximum_inputs
   else
        - take first item in list of first currency and add it to current utxos/remove from user utxos
   stealth_merge(new_current_utxos, new_user_utxos
end
```

Round 0: [5 ETH, 10 OMG], [10 ETH, 15 ETH, 5 OMG]
Round 1: [5 ETH, 10 ETH, 10 OMG], [15 ETH, 5 OMG]
Round 2:
