### ISSUE TITLE
Set Conn remote_ip based on X-Forwarded-For header

### ISSUE THREAD

**Issue by arthurk** [omgnetwork/elixir-omg#1657]
This is a small change to improve the error reporting in Sentry. When displaying exceptions it uses Conn.remote_ip as the "User" but since the app is running behind a proxy we get the proxy server ip (::ffff:10.0.0.5) instead of the real user ip:

<img width="821" alt="Screen Shot 2020-07-21 at 6 19 24 PM" src="https://user-images.githubusercontent.com/23406/88042579-bae35580-cb7e-11ea-985e-c510b77f5e75.png">

To fix this we can set the remote_ip based on the X-Forwarded-For headers. For example with https://github.com/ajvondrak/remote_ip

**Comment by unnawut** [comment]
Added to Gold Team backlog for @T-Dnzt 's prioritization
