### ISSUE TITLE
Flaky system or test on reorg condition

### ISSUE THREAD

**Issue by boolafish** [omgnetwork/elixir-omg#1675]
We have observed that the reorg test would fail in CI: https://app.circleci.com/pipelines/github/omgnetwork/elixir-omg/7884/workflows/174a5a23-4817-4de3-8afe-a478d9f12ba4/jobs/72735

Not sure it is our system is really flaky on reorg or the test is flaky though.

**Comment by ayrat555** [comment]
Two kinds of errors I saw:
1. Tests are timing out during account creation and unlocking on both geth nodes. After I increased timeout for account creation, I haven't seen this error anymore
2. Tests are failing with wrong balances (on the childchain and the rootchain). I added additional checks to the reorg function to make sure nodes have the same latest block after reorg. I think it helped but still, tests are failing sometimes.
