### ISSUE TITLE
elixir-omg Release Notes

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#582]
having a centralized wiki/page/site/section for Release Notes.

Note should Include:
- known issues
- version 
- features
- improvements
- possibly even endpoints/contract address for each release

Suggestion: a GH wiki might be a good place for it https://github.com/omisego/elixir-omg/wiki

Also, given that `plasma-contract` and `elixir-omg` is on separate repos, do we want to keep the notes separate or in the same wiki ?

**Comment by InoMurko** [comment]
Also: https://github.com/omisego/elixir-omg/issues/1067

**Comment by unnawut** [comment]
Is this it? https://github.com/omisego/elixir-omg/blob/master/CHANGELOG.md

**Comment by unnawut** [comment]
closing until clearer requirements
