### ISSUE TITLE
Figure out Zero downtime upgrades for child chain

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/elixir-omg#710]
:clipboard: [PLAN-198](https://omisego.atlassian.net/browse/PLAN-198)

As a user, I can continue to submit transactions to the child chain even through an upgrade, so that I don’t have downtime

- [ ] figure out architecture
- [ ] break up into engineering stories
- [ ] #559
- [x] https://github.com/omisego/elixir-omg/issues/710

**Comment by boolafish** [comment]
Here is a previous research idea from the contract upgrade side: [doc here](https://omisego.atlassian.net/wiki/spaces/RES/pages/16810033/Smart+Contract+Upgrade+with+Testing+Phase+High+Level+Design?atlOrigin=eyJpIjoiMWZiY2Q3NDE5NzM5NDU1NzliOWZjMjcxMDBiMmY0YWEiLCJwIjoiYyJ9).

Might be related.

**Comment by InoMurko** [comment]
https://github.com/omisego/elixir-omg/issues/849 is related to this.
