### ISSUE TITLE
Design Network API to be easily consumed by users

### ISSUE THREAD

**Issue by achiurizo** [omgnetwork/elixir-omg#720]
:clipboard: [PLAN-221](https://omisego.atlassian.net/browse/PLAN-221)

As an eWallet Provider and DEX venue building on the OMG network, 
I would like to have a holistically consistent API to consume from, 
So that I can build my application without too much complexity.

As an eWallet provider, I would like to the logs of historical byzantine events so that in case my connections have dropped off- I can retrieve the past events I’ve missed and maintained consistent state- ensuring that invalid actions have already been challenged.

As both eWallet and an Exchange, I would like to be able to replay the transactions from a certain number of blocks, so that in case my connections have dropped off- I can retrieve the past transactions I’ve missed and maintained consistent state.

As an eWallet provider and an Exchange, I would like to be able to consume all data from the watcher with an additional blknum tag as a sequence number, so that I can maintain consistent state

**Comment by pnowosie** [comment]
@achiurizo We have unified API to eWallet http-rpc (#264) model, docs are in swagger format.
What else is left ❓

**Comment by pdobacz** [comment]
IIRC this was reliant upon #716 and getting detailed feedback from eWallet/DEX venue etc.

**Comment by unnawut** [comment]
Stale requirements. Can reopen and polish when needed
