### ISSUE TITLE
Operator to call process exits for user

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#843]
NET-69

**Story**

As an wallet/ application provider, I would like to not have to call processExit() for my users, so that my user can have one less exit step to be worried about.

**Benefit**
- this way people will be able to get their funds right away after the challenge period is over

**Comment by jrhite** [comment]
I'm in the thick of this. Also just went through a lot of this with `omg-js`. Maybe I should take a look at this @Pongch?

It's very high-related to omisego/omg-block-explorer/issues/14. Without watcher calling the contract's `processExits()` then I can't get the transaction id. On the other hand, even if watcher is calling `processExits()` it is still possible for others to call `processExits()` too, so watcher will either need to poll or listen on a ws for txn data from ethereum.

```
Plasma Txn #1
    -> UTXO & Address #1   ---
                               >   Ethereum Txn Hash #1
    -> UTXO & Address #2   ---
    -> UTXO & Address #3   --- >   Ethereum Txn Hash #2
```

**Comment by pdobacz** [comment]
Hey, note that there might be an option to just keep it very simple and have the service:
 - poll the root chain contract (can be quite infrequent, every ethereum block)
 - during that poll figure out whether there is a mature exit on the top of the PriorityQueue
 - if yes, call `processExits` 

Repeat the above for every token address enrolled.

**Comment by InoMurko** [comment]
Leaving my findings here:
PriorityQueue contract has:
```
/*
     * Read-only functions
     */

    function minChild(uint256 i)
        public
        view
        returns (uint256)
    {
        return queue.minChild(i);
    }

    /**
     * @dev Returns the top element of the heap.
     * @return The smallest element in the priority queue.
     */
    function getMin()
        public
        view
        returns (uint256)
    {
        return queue.getMin();
    }

    function currentSize()
        external
        view
        returns (uint256)
    {
        return queue.getCurrentSize();
    }
```

**Comment by Pongch** [comment]
Note on this task: lets hold off on this task for now. There's a specific questions that needs to be confidently answered about the frequency and amount of exit to process which will inform the design decision.

Thanks @InoMurko

**Comment by boolafish** [comment]
Just curious and wanna learn, do you mind to share the findings? @Pongch

**Comment by unnawut** [comment]
Stale issue + can reopen when needed. Also might be economically feasible only after https://github.com/omgnetwork/plasma-contracts/issues/607
