### ISSUE TITLE
configure watcher to the correct contract addresses

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#846]
NET-75

As a Developer running the watcher,I would like to configure my watcher to point to correct abstract contract addresses, so that my watcher may function and help me secure my funds

**Risk**

- upgrades could be considered by the watcher as a byzantine event

- no way to tell all the watchers to switch addresses- since there is no P2P communication between watchers

**Value:**

allows watcher to switch to new smart contracts with new features

**Comment by InoMurko** [comment]
Lets try to figure out more concrete requirements.

How would a customer that runs watcher want to `invoke` this process?
- HTTP request to watcher?
- Watcher restart?
- OTP release command? https://hexdocs.pm/distillery/extensibility/custom_commands.html

**Comment by Pongch** [comment]
What is the way that the watcher is currently used to configure the correct smart contract address ? From my understanding- after talking to @pdobacz , I think watcher is required to be updated to the latest version anyways. The biggest barrier to this issue is that the current watcher must know the contracts/child chain is being upgraded, so it does not show up byzantine events. 

If I understand correctly, the steps should be:
1. watcher detects that the child chain is being upgraded
2. watcher alerts user to upgrade to latest watcher version
3. watcher upgraded and redeployed with the correct smart contract address(es)

CC @boolafish as well since we have talked about upgrade experience.

**Comment by unnawut** [comment]
Closing as this requires a clear picture of what an upgrade would look like from the contract side of things
