### ISSUE TITLE
Operator can make smart contract upgrades

### ISSUE THREAD

**Issue by Pongch** [omgnetwork/elixir-omg#847]
NET-76

As an operator running the child chain service,I would like to perform upgrade to my smart contracts, so that we can have new functionalities on the child chain

**Comment by jbunce** [comment]
I'm not sure this is the best approach. We're working to move the contract mechanism away from the operator. I don't like the idea of allowing the Childchain to do this as it means we would allow the operator access to the authority address. Let's have a chat about how we can do this without using `elixir-omg`.

**Comment by Pongch** [comment]
I agree with this @jbunce let's have an upgrade mechanism be handled by another keypair or wallet. I have a few ideas around this but we should explore options.

**Comment by boolafish** [comment]
oh interesting. Please sync in Plasma-contract if any decision is made on this topic as this definitely need contract support

**Comment by paulperegud** [comment]
If we will replace keypair with multisig, we can use individual signatures as a "I've checked everything, everything is fine, we can roll the upgrade" flag. Basically a mean to decrease the amount of errors by increasing amount of eyes / skin in the game.

**Comment by unnawut** [comment]
doesn't sound like a chch thing
