### ISSUE TITLE
Child chain server run in integration tests obfuscates its crashes

### ISSUE THREAD

**Issue by pdobacz** [omgnetwork/elixir-omg#880]
Child chain server run in integration tests obfuscates its crashes, printing out `{:exit_status 256}` regardless of what happened. (**NOTE** this is in `omg_watcher` integration tests!)

Currently, to see what's on, one needs to bump the logging level for the `test` env (`config/test.exs`) to `debug` and dig through a lot of logs.

It would be nice to have the reason of the crash somehow propagate, or at least to always be able to get >=`warn` level logs out of the child chain instance running under the hood.

This `256` probably comes out of `exexec` or `mix` which are used to orchestrate the child chain instance when integration-testing the watcher. I'm guessing tweaking the configuration of one of these, might lead to an easy fix.

### How to reproduce

Just put something very breaking inside the child chain code, example:

```
    _ = Logger.info("Starting #{inspect(__MODULE__)}", :fdsss, :fds, "fds")
```
in `apps/omg_child_chain/lib/omg_child_chain/application.ex:27`

**Comment by achiurizo** [comment]
@pdobacz is this still an issue?

**Comment by pdobacz** [comment]
yep I think so, but I think a fix that is currently planned, is the full cabbageization of integration tests and removing the `mix_based_blah_blah` setups for testing, which are causing the problem.

Unless someone wants to look into very badly and manages to find a quick solution to the problem.

**Comment by unnawut** [comment]
we're moving away from fixtures
