### ISSUE TITLE
If set contract release task can't reach exchanger yield error

### ISSUE THREAD

**Issue by InoMurko** [omgnetwork/elixir-omg#959]
If `OMG.Eth.ReleaseTasks.SetContract` has `CONTRACT_EXCHANGER_URL` set, but that url is not reachable, yeild an explanation and exit.

`{:ok, %{body: body}} = HTTPoison.get(exchanger)`

wrap in a try catch and rescue with `exit/1`.

**Comment by unnawut** [comment]
Already implemented in https://github.com/omgnetwork/elixir-omg/blob/master/apps/omg_eth/lib/omg_eth/release_tasks/set_contract.ex#L52-L57
